### ISSUE TITLE
Got a question about the auto-saving for article, not a issue

### ISSUE THREAD

**Issue by boyishwei** [abuiles/borrowers#16]
Hi
I'm reading the `Ember cli 101` and I got a question about the `article` _Auto-Save_ part.

In the section about implement "Auto-Save", we need to change the `app/templates/components/articles/article-row.hbs` from:

```
<td>
{{#if article.isSaving}}
   <p>Saving ...</p>
{{else if article.hasDirtyAttributes}}
  <button {{action "saveArticle" article}}>Save</button>
{{/if}}
</td>
```

to:

```
<td>
{{#if article.isSaving}} 
  <p>Saving ...</p>
{{/if}}
</td>
```

and also update the action in `app/components/articles/article-row.js` to:

```
saveArticle() {
  let article = this.get('article');
  if (article.get('hasDirtyAttributes')) { 
      this.sendAction('save', article);
    }
  }
```

then, if we change the state of a article, it will auto-save.

But I really didn't understand how it auto-saved, previously there is a `Save` button, once we click on the `Save` button, it will execute the action `saveArticle`, but after remove it from the page, how would it trigger the `saveArticle` to save the article. 

I'm reading the book in Chinese version, maybe something is missing after the translate, I'm not sure.

May it's a stupid question, :), but looking forward of you reply. 

Thanks in advance!

**Comment by sagaban** [comment]
Hi Wei! 
This line :
{{#x-select value=article.state action="saveArticle"}}
in the "borrowers/app/templates/components/articles/article-row.hbs” file is the one that trigger the action saveArticle
every time the select an state from the drop-down list.

I hope this could answer you question!

Regards

Santiago

**Comment by boyishwei** [comment]
oh, it is, I just focus on the change that made in the `app/components/articles/article-row.js`, didn't notice that a `action="saveArticle"` was added in the `xselect`. 

Thank you  very much, sagaban! :)
