### ISSUE TITLE
Cancel action in FriendsEditController

### ISSUE THREAD

**Issue by rkrdo** [abuiles/borrowers#2]
Hey Adolfo,

I just implemented the Cancel action for the friends/edit controller as seen [here](https://github.com/abuiles/borrowers/blob/79601014b1567e0ef5c2fda2cd300f3483fa6b22/app/controllers/friends/edit.js) but whenever I click the cancel button, it redirects to `http://localhost:4200/friends/undefined`

I'm using the latest version of your book and ember-cli 0.1.5

My guess would be to use `this.get('model')` instead of just `this` in the [route transition](https://github.com/abuiles/borrowers/blob/79601014b1567e0ef5c2fda2cd300f3483fa6b22/app/controllers/friends/edit.js#L6)

**Comment by tylergaw** [comment]
Ran into the same thing. @rkrdo using `this.get('model')` worked for me too.

Might be good to add an issue in the book repo? https://github.com/abuiles/ember-cli-101-errata/issues

**Comment by tylergaw** [comment]
I looked a little harder and found an existing issue for this https://github.com/abuiles/ember-cli-101-errata/issues/89

**Comment by rkrdo** [comment]
oh, didn't realize there was a repo specific for errata, thanks @tylergaw
