### ISSUE TITLE
Page 60: linking to /friends/:friend_id/articles from friends index results in Error 'Uncaught Error: More context objects were passed than there are dynamic segments for the route: articles'

### ISSUE THREAD

**Issue by akharris** [abuiles/borrowers#20]
I'm running into an issue at Page 60 in the 'Nested Articles Index' section of the book. At the part where you write

> If we visit a friend profile, we won’t see anything related with the articles index route. Why? Well,
> we are not visiting that route, that’s why. To get to the articles index route, we need to modify the
> link-to in app/templates/friends/index.hbs to reference the route articles instead of friends.show.
> **We’ll still pass the friend as an argument since the route articles is nested under friends.show 
> and it has the dynamic segment :friend_id.**

so I updated the /app/templates/friends/index.hbs

``` html
<table class="primary">
  <thead>
    <tr>
      <th>Name</th>
      <th>Articles</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {{#each model as |friend|}}
      <tr>
        <!-- update the link to 'articles' as specified in the passage above -->
        <td>{{link-to friend.fullName "articles" friend}}</td>
        <td>{{friend.totalArticles}}</td>
        <td><a href="#"{{action 'delete' friend}}>Delete</a></td>
      </tr>
    {{/each}}
  </tbody>
</table>
```

which results in the `Uncaught Error: More context objects were passed than there are dynamic segments for the route: articles` error from the browser console.

![screen shot 2015-12-31 at 9 33 38 am](https://cloud.githubusercontent.com/assets/5504772/12065249/ac9e91f4-afa1-11e5-922d-bf72aa3f22aa.png)

my /app/router.js looks like this

``` javascript
import Ember from 'ember';
import config from './config/environment';

const Router = Ember.Router.extend({
  location: config.locationType
});

Router.map(function() {
  this.route('friends', function() {
    this.route('new');

    this.route('show', {
      path: ':friend_id'
    }, function() {
      this.route('articles', {resetNamespace: true}, function() {
      });
    });

    this.route('edit', {
      path: ':friend_id/edit'
    });

  });
  this.route('articles');
});

export default Router;
```

I'm going to experiment with placing the articles index template in different places depending on what the ember inspector tells me. I'll update the issue if I find a solution.

**Comment by Stas-Buzunko** [comment]
Hello!
Have you found a solution?

**Comment by abuiles** [comment]
@Stas-Buzunko are you experimenting this issue? can you create a jsbin showing it?

**Comment by Stas-Buzunko** [comment]
Yes, I do. I don't know how to create a jsbin, well I can find it out if you need, but my code is exactly the same as above and the same error

**Comment by Stas-Buzunko** [comment]
I also tried to use friend.id instead of friend {{link-to friend.fullName "articles" friend.id}} but get the same error and have no idea how to fix this :)

**Comment by abuiles** [comment]
@Stas-Buzunko I'll check at this later today and let you know what's going :)

**Comment by Stas-Buzunko** [comment]
Thank you! I like your tutorial very much, for sure the best one I've done since started learning ember, but stuck there :(

**Comment by abuiles** [comment]
@Stas-Buzunko can you try `{{link-to friend.fullName "friends.show.articles" friend}}`

**Comment by Stas-Buzunko** [comment]
Uncaught Error: There is no route named friends.show.articles

my router.js show route:

```
this.route('show', {
path: ':friend_id'
  }, function() {
    this.route('articles', {resetNamespace: true}, function() {
  });
});
```

**Comment by abuiles** [comment]
ok, sorry, I'm kind of busy right now, but will check out later today :)

## 

Adolfo Builes

**Comment by Stas-Buzunko** [comment]
Tried a lot of stuff, and got confused what exactly worked.
But as I understand (I can be mistaken :)) all we need to change is to add a block to link-to
{{#link-to "articles" friend}}{{friend.fullName}}{{/link-to}}
This works for me :)
![screenshot from 2016-02-17 20 19 23](https://cloud.githubusercontent.com/assets/12331100/13119848/ca226f38-d5b3-11e5-8ecc-bc2ecf4fcb93.png)

**Comment by Stas-Buzunko** [comment]
The only question I have is whether I have the right URL showing articles:  http://localhost:4200/friends/14839/articles ?

**Comment by abuiles** [comment]
yes, that looks correct :)

## 

Adolfo Builes

**Comment by DrSayre** [comment]
Has anybody else had trouble with this?  I tried what @Stas-Buzunko has, but still getting the same error.  Here is my router:

```
import Ember from 'ember';
import config from './config/environment';

const Router = Ember.Router.extend({
  location: config.locationType
});

Router.map(function() {
  this.route('friends', function() {
    this.route('new');

    this.route('show', {
      path: ':friend_id'
    }, function() {
      this.route('articles', {resetNamespace: true}, function() {
      });
    });

    this.route('edit', {
      path: ':friend_id/edit'
    });
  });
  this.route('articles');
});

export default Router;
```

I have tried `{{#link-to "articles" friend.id}} {{friend.fullName}} {{/link-to}}` and `{{link-to friend.fullName "articles" friend}}` with both getting this error.

**Comment by DrSayre** [comment]
Ok I found my problem!  I had the articles route it's outside the friends path.  Once I got rid of that and only had it under friends, both version of link-to worked!

**Comment by stefek99** [comment]
@AKHarris I know why is that! @DrSayre explains that:

> I had the articles route it's outside the friends path.

No worries, you are in a good company, I made the same copy & paste error...

_(and that's how I landed in this GitHub issue)_

Your code: https://github.com/abuiles/borrowers/issues/20#issue-124476936

![page_60__linking_to__friends__friend_id_articles_from_friends_index_results_in_error__uncaught_error__more_context_objects_were_passed_than_there_are_dynamic_segments_for_the_route__articles__ _issue__20_ _abuiles_borrowers](https://cloud.githubusercontent.com/assets/249703/15708380/9a8379a0-27fe-11e6-9ea4-f34cc4a1fb63.png)

**Comment by abuiles** [comment]
Thanks everyone! I'm working on an update of the book, and this will be fixed there. ...

For the interested, this is the repo https://github.com/abuiles/borrowers-2016 and this is the branch in the book https://github.com/abuiles/ember-101/pull/65

**Comment by akharris** [comment]
@stefek99 awesome thanks!

**Comment by abuiles** [comment]
@AKHarris I just released a new version of the book ;), where this is fixed.

Thanks everyone!
