### ISSUE TITLE
pg 50: [SimpleConcat: Concat: Vendor Styles/assets/vendor.css] failed error with addition of picnic

### ISSUE THREAD

**Issue by syivanes** [abuiles/borrowers#22]
```
The Broccoli Plugin: [SimpleConcat: Concat: Vendor Styles/assets/vendor.css] failed with:
Error: ENOENT: no such file or directory
```

getting this right at the start of the server, browser not opening any pages now.

**Comment by syivanes** [comment]
and the fix is... in ember-cli-build.js, you should only have this line for Picnic 
`app.import('bower_components/picnic/picnic.min.css');`
there is no plugins.min.css file anymore and picnic.min.css is in Picnic's root directory, not picnic/releases.

**Comment by abuiles** [comment]
Thanks! I'll keep this in mind for the next update.
