### ISSUE TITLE
Error with {{#each model as |article|}} 

### ISSUE THREAD

**Issue by rubenmoya** [abuiles/borrowers#4]
Hi!

I'm on the page 71 of the book, and when I try to use the article-row component I get this error:

```
File: borrowers/templates/articles/index.hbs
Parse error on line 12:
...   {{#each model as |article|}}      {{
-----------------------^
Expecting 'CLOSE', 'CLOSE_UNESCAPED', 'STRING', 'INTEGER', 'BOOLEAN', 'OPEN_SEXPR', 'CLOSE_SEXPR', 'ID', 'EQUALS', 'DATA', 'SEP', got 'INVALID'
```

This is my articles/index.hbs template:

```
<table class="primary">
  <thead>
    <tr>
      <th>Description</th>
      <th>Borrowed since</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {{#each model as |article|}}
      {{articles/article-row article=article save="save" articleStates=possibleStates}}
    {{/each}}
  </tbody>
</table>
```

I really don't know what I'm missing here, I checked the book and the repo a couple of times, so... what I'm missing?

**Comment by demental** [comment]
I have the same issue, I guess this is due to some change in handlebars in newer versions of Ember. I'm running ember 1.8.1, while Ember version [here](https://github.com/abuiles/borrowers/blob/master/bower.json#L5) is 1.10.0. 

So upgrading ember to 1.10 should fix the problem. Sorry I'm no bower specialist so I'll try to figure out how to do this,...
FYI even using the previous hbs syntax (each article in model), I have an issue with the namespaced article/article-row component not being displayed.

**Comment by abuiles** [comment]
Hey,

I'll a release shortly fixing some issues and also I'll send a general note that we need to be in the latest version of ember-cli.

If you are using an old version, just replace it in your package, then npm install and finally do ember init, that will update the necessary dependencies.

—

**Comment by demental** [comment]
Done, following the instructions in the ember-cli release repo : https://github.com/ember-cli/ember-cli/releases/tag/v0.2.0-beta.1

I just had to re-add the picnic dependency in bower.json, apart from this the app is back on tracks :D

**Comment by abuiles** [comment]
Awesome!

I also added a section about upgrading :), so that could help too.

## 

Adolfo Builes

**Comment by iamalex2** [comment]
how do you use it without upgrading as in v 0.1.15

**Comment by stefek99** [comment]
Ahhh... I was following the book and at some point it wasn't working for me. So I decided to clone repo and move back in the history.

I'm on the train now (unreliable 3G connection) so I'm copying `node_modules` (more than 100MB, almost 30,000 files) from another project and I'll see how it goes :)
