### ISSUE TITLE
Deletion on Friends Show Route

### ISSUE THREAD

**Issue by camskene** [abuiles/borrowers#9]
On page 49 (pdf) it is stated:
 `To support deletion on Friends Show Route, we just need to add the same link[...]` 
referring to the delete link added on the previous page:
 `<a href="#" {{action "delete" friend}}>Delete</a>`

However to delete from the friends show route the link would need to be:
`<a href="#" {{action "delete"` **model**`}}>Delete</a>`

**Comment by jimbeaudoin** [comment]
@camskene I reached the same conclusion. I think you are correct. @abuiles ?

**Comment by abuiles** [comment]
@camskene @jimbeaudoin hey! thanks, you are correct, I'll fix this on the book :) leaving open until I do so

**Comment by abuiles** [comment]
Fixed, thanks!
